name: 👷Flow

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:
  merge_group:

jobs:
  lint:
    uses: mraniki/coding_toolset/.github/workflows/🦺Lint.yml@main
    secrets: inherit
  test:
    needs: [lint]
    uses: mraniki/coding_toolset/.github/workflows/🧪Test.yml@main
    secrets: inherit
  build:
    needs: [lint]
    uses: mraniki/coding_toolset/.github/workflows/🐍Build.yml@main
    secrets: inherit
  release:
    needs: [lint]
    uses: mraniki/coding_toolset/.github/workflows/📦Release.yml@main
    with:
      settings_publish: false
    secrets: inherit
  #pr-merge:
    #needs: [build, test,release]
    #uses: mraniki/coding_toolset/.github/workflows/⛙Automerge.yml@main
    #secrets: inherit

  mirror:
    needs: [release]
    uses: mraniki/coding_toolset/.github/workflows/🪞Mirror.yml@main
    secrets: inherit
